### ISSUE TITLE
About 10x higher values reported for network, disk - not related to partitions

### ISSUE THREAD

**Issue by Korkman** [scottchiefbaker/dool#33]
Tested on Debian Jessie, Debian Buster, Debian Bullseye, Dool 1.0.0, 1.1.0 and master:

Both network and disk usage is reported about 10x higher than original dstat does, even with the devices explicitly specified like this:
`dool --cpu --net -N ens3 --disk -D vda3 --load --time`

Here is a comparison:
![grafik](https://user-images.githubusercontent.com/3186931/219944588-83ca221f-adba-44d2-a92b-5fff1f06730a.png)

The 520k write was created with:
`dd if=/dev/zero of=testfile.dd bs=512 count=1000`

Edit: also tested on Ubuntu 22.04 LTS Live ISO with no localization (english)

**Comment by mckellygit** [comment]
If you add --bytes does it become correct ?

**Comment by Korkman** [comment]
Ideally one would have a per-plugin default (and setting), because MBit/s makes total sense for network.

**Comment by mckellygit** [comment]
I was ok with bytes for net also, I changed the default in my local copy:
```
 class Options:
     def __init__(self, args):
         self.args         = args
-        self.bits         = True
+        self.bits         = False
         self.blackonwhite = False
         self.count        = -1
```

**Comment by Korkman** [comment]
Changed it for me with the equivalent of an alias which always adds --bytes.

Closing because basically just a misunderstanding, might open a feature request for this at a later date.
