### ISSUE TITLE
CSV output in bytes with --bits flag

### ISSUE THREAD

**Issue by kmac** [scottchiefbaker/dool#45]
##### SUMMARY

With `dool --bits -n --output test.csv --display`, the values in test.csv are in bytes.  I'm not sure about other values, but it's very noticeable with the network values, and is a cause for confusion - it can be a gotcha if you're not aware of it.

I think there are two possible choices here:  1) Change the output values to bits in the CSV output, or 2) warn the user when --bits + --output is used.  Perhaps a simple upfront text warning log to stderr would be sufficient?   I'd have appreciated it, rather than going back to regenerate my charts.

##### ISSUE TYPE

 - Bug Report

##### DSTAT VERSION

All recent dool versions have this behaviour.

##### OS / ENVIRONMENT

- Debian
- Arch

##### STEPS TO REPRODUCE

From master branch:

```
$ dool -n --bits --output /tmp/test.csv --display
┄net/total┄
 recv  send
   0     0
4229K 4257K
3408K 3410K
5543K 5550K
1327K 1339K
7266K 7268K

$ cat /tmp/test.csv
"dool 1.2.0 CSV output"
"Author:","Scott Baker",,,,"URL:","https://github.com/scottchiefbaker/dool/"
"Host:","yow-kmacleod-lx",,,,"User:","kmacleod"
"Cmdline:","./dool -n --bits --output /tmp/test.csv --display",,,,"Date:","13 Jul 2023 13:34:38 EDT"
"net/total",
"recv","send"
0,0
528572,532142
426061,426269
692840,693721
165884,167410
908268,908512
```

##### EXPECTED RESULTS

Using --bits I had expected the CSV values to be bits as well.

##### ACTUAL RESULTS

CSV values are bytes

**Comment by scottchiefbaker** [comment]
This is 100% a valid bug and I will investigate it. It's in a complicated piece of the code so it might be a complicated fix.

**Comment by scottchiefbaker** [comment]
@kmac the fix ended up NOT being quite as gnarly as I was thinking. Please try the code on `next` branch and see if that fixes your problem. I'm seeing parity between the on screen output and the CSV output now so I think it's fixed.

**Comment by kmac** [comment]
Thank you @scottchiefbaker - I haven't had time to test this but the change looks good.
