### ISSUE TITLE
Reason for changing unit_lo from darkgray to gray?

### ISSUE THREAD

**Issue by exuvo** [scottchiefbaker/dool#52]
I finally took the dive to use dool instead of dstat and with --bytes --color16 --asci it looks almost identical to dstat (which i prefer the look of).

But i was wondering why you changed the color of units and 0s from darkgray to gray in https://github.com/scottchiefbaker/dool/commit/79d3b6c6417ef7143b47448acbdf04cc267d5208?

Personally i prefer the darkgray for the usually unimportant values to make the important ones stand out more.

**Comment by scottchiefbaker** [comment]
I forget exactly why... it was four years ago. I'm pretty sure it just looked better on my terminal. If you like it as `darkgray` it's a pretty simple change to the source code.

**Comment by exuvo** [comment]
Oh yes i have already changed it on my end just wondered if there was a bigger reason behind it.
