### ISSUE TITLE
Per process stats

### ISSUE THREAD

**Issue by NasdaqGodzilla** [scottchiefbaker/dool#56]
##### SUMMARY

Is there any plan to add independent stat for each process?

##### ISSUE TYPE

 - Feature Idea

##### DOOL VERSION

v1.3.0

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

Per process stats would be very helpful

##### EXPECTED RESULTS

Per PID stat, like top.

##### ACTUAL RESULTS

New feature

**Comment by scottchiefbaker** [comment]
This has not come up before. I'm not sure what we could offer that a simple:

```
top -p 1234
```

doesn't already do? We have some of the framework in `top-io` and `--top-cpu` but I don't see how showing an individual pid would fit in the `dool` style of output. 

How are you thinking it would look/work?

**Comment by kirito41dd** [comment]
I also need the feature to collect specified pid information.

**Comment by scottchiefbaker** [comment]
There is a `--pid-info 1234` plugin that got released with the last version of Dool. It's functional but limited.
