### ISSUE TITLE
dool can't open subprocess commands (like with --mysql-io)

### ISSUE THREAD

**Issue by andrew-niaid** [scottchiefbaker/dool#57]
On Rocky 9.2 with the default python (3.9.16), dool produces the error: `module 'os' has no attribute 'popen3'` when trying to use options that require spawning a subprocess such as --mysql-io. 

It looks like the `import asubprocess` in the try block fails because `asubprocess` isn't valid, so it then tries the `os.popen3()` in the exception, but that's not valid on python 3.9. 

Should `import asubprocess` really be `import subprocess`?

https://github.com/scottchiefbaker/dool/blob/332b82832b1a4394238c4ffc922308527bf1fbba/dool#L1773-L1779

**Comment by scottchiefbaker** [comment]
Looks like Python 3 completely dropped `os.popen*()`? Either way it probably should never hit that code, as it does appear `subprocess.Popen()` is [still valid](https://docs.python.org/3/library/subprocess.html#subprocess.Popen). Perhaps that import is a typo and that's the problem? If you fix the typo does that solve the issue?

Sounds like either way we need to update the exception catching to error out?

**Comment by andrew-niaid** [comment]
Yes, this appears to work!

**Comment by scottchiefbaker** [comment]
This should be fixed now.
