### ISSUE TITLE
disk-util: filter loop devices

### ISSUE THREAD

**Issue by Zahrun** [scottchiefbaker/dool#58]
##### SUMMARY

It would be nice if we could filter the loop devices in disk-util

##### ISSUE TYPE

 - Feature Idea

##### DOOL VERSION

1.3.0

##### OS / ENVIRONMENT

Tuxedo OS 2

##### STEPS TO REPRODUCE

`dool --disk-util`

##### EXPECTED RESULTS

Monitor the utilization of non-loop disks only

##### ACTUAL RESULTS

dool shows all the loop devices

![image](https://github.com/scottchiefbaker/dool/assets/10415894/5a6cb5b5-91f5-40f8-8ea0-6a0ad1b31d4f)

**Comment by scottchiefbaker** [comment]
Can you post the text from `/proc/diskstats` so I can see what we're reading.

**Comment by scottchiefbaker** [comment]
You can already filter `--disk-util` by using the `-D` filter like this:

`dool --disk-util -D sda,sdd`

If this is not sufficient let us know.

**Comment by Zahrun** [comment]
Oh that totally works, thank you
