### ISSUE TITLE
Disk plugin shows far too large values

### ISSUE THREAD

**Issue by felf** [scottchiefbaker/dool#64]
##### SUMMARY
Arch’s pacman suggested dool as replacement for dstat. So I installed it. But I quickly noticed that what it showed me was not plausible, as the disk I/O values war far too large.

##### ISSUE TYPE
 - Bug Report

##### DOOL VERSION
1.3.1

##### OS / ENVIRONMENT
Arch Linux standard packages.

##### STEPS TO REPRODUCE
Start dool with the disk plugin.

##### EXPECTED RESULTS
It should show accurate values. :)

##### ACTUAL RESULTS
Dool shows disk I/O values that are far too large. I compared its output with dstat, of course, but also with KDE system monitor, htop and glances. All showed (roughly) the same as dsta: when my KDE baloo file indexer was running amok, it caused permanent load of around 140 MB/s according to the aforementioned programs, but dool showed 900..1200 MB/s. This isn’t even possible, because the SSD in question is attached via PCIe 2.0×2, which tops out at 1 GB/s.

I did another test, reading from a SATA ssd with dd. Technically, SATA is limited to 550 MB/s, but dool was about one order of magnitude off. See screenshot:
![dool](https://github.com/scottchiefbaker/dool/assets/25027583/e9fc9d01-294e-4cbe-a80d-d1efec75caf7)

**Comment by scottchiefbaker** [comment]
Dool defaults to measure network and disk traffic in bits instead of bytes. Try using the `--bytes` option and see if you get the numbers you expect.

**Comment by felf** [comment]
Now that you mention it, I do notice the lowercase b in the network column of my screenshot. Thanks.
