### ISSUE TITLE
Dool showing throughput numbers 10x Dstat

### ISSUE THREAD

**Issue by githubjsorg** [scottchiefbaker/dool#71]
##### SUMMARY
Dool IO numbers for disk and network are showing 10X what dstat shows on the same machine at the same time. I know dool numbers are inflated as the numbers shown for the devices is higher than expected given the activity of the system and in the case of the network numbers, impossible.

##### ISSUE TYPE
 - Bug Report

##### DOOL VERSION
Dool 1.3.1

##### OS / ENVIRONMENT
Platform posix/linux
Kernel 6.5.13-3-pve
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

pveversion
pve-manager/8.2.2/9355359cd7afbae4 (running kernel: 6.5.13-3-pve)

cat /etc/debian_version
12.5

uname -a
6.5.13-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.13-3 (2024-03-20T10:45Z) x86_64 GNU/Linux

##### STEPS TO REPRODUCE
Compare dstat and dool output for disk and net IO

##### EXPECTED RESULTS
The dool and dstat numbers to match. Or at least for the dool numbers to be realistic.

##### ACTUAL RESULTS
The dool numbers for IO appear to be drastically inflated and in the case of network IO impossible.

For example:
Dstat on top. Dool on bottom. Both running simultaneously on the same machine. Note: This system only has a 1GBit network interface so multiple 100s of MB/sec on eth1 is impossible.
![image](https://github.com/scottchiefbaker/dool/assets/12621019/bd459815-7e20-4756-bcb8-5644e75a0100)

**Comment by scottchiefbaker** [comment]
Please read: https://github.com/scottchiefbaker/dool?tab=readme-ov-file#bits-vs-bytes
