### ISSUE TITLE
Plugins not available when installing via pip

### ISSUE THREAD

**Issue by benfishbus** [scottchiefbaker/dool#73]
##### SUMMARY

Many (all?) plugins give an error when Dool is installed using pip.

##### ISSUE TYPE

 - Bug Report

##### DOOL VERSION

1.3.2

##### OS / ENVIRONMENT

Platform posix/linux
Kernel 6.1.79-Unraid
Python 3.9.10 (main, Jan 16 2022, 02:41:55) 
[GCC 11.2.0]

##### STEPS TO REPRODUCE

```
pip install dool
dool --top-io
```

##### EXPECTED RESULTS

Start the top-io plugin.

##### ACTUAL RESULTS

`dool: option --top-io not recognized, try dool -h for a list of all the options`

**Comment by scottchiefbaker** [comment]
Dool checks for plugins in:

```
    os.path.expanduser('~/.dool/'),                              # home + /.dool/
    os.path.abspath(os.path.dirname(sys.argv[0])) + '/plugins/', # binary path + /plugins/
    '/usr/share/dool/',
    '/usr/local/share/dool/',
```

Do you see any files in any of those locations? Running `dool --version` will list all the plugins it finds, and what directory they're located in.

**Comment by raylu** [comment]
oh I knew about this when I set up the packaging. see #50
> the main problem, though, is `plugins/`. it can't find any after installing

I wrote some more about what it would take to make the plugins installable and importable, but after
> The plugins are nice, but not required.

I decided to forget about it

**Comment by scottchiefbaker** [comment]
@raylu is this something we want to include in the next version that gets published? I don't know how complicated it would be.

**Comment by raylu** [comment]
@benfishbus give https://test.pypi.org/project/dool/1.3.3/ a whirl

**Comment by scottchiefbaker** [comment]
@benfishbus is this issue resolved?

**Comment by benfishbus** [comment]
Had to educate myself on installing stuff from test. It is working for me!
