### ISSUE TITLE
Support time formatting

### ISSUE THREAD

**Issue by jsirianni** [scottchiefbaker/dool#76]
##### SUMMARY

The `--time` flag outputs time like this `Sep-07 19:40:02,`. I have an issue where I require my time data to fit a certain format, something without spaces to be specific. Of course, I can do some post processing on the CSV output to get the desired format but that is not ideal.

Something like [strptime](https://pubs.opengroup.org/onlinepubs/007904875/functions/strptime.html) would be great, or whatever makes sense for this application.

##### ISSUE TYPE

 - Feature Idea

##### DOOL VERSION

```
Dool 1.3.2
Written by Scott Baker <scott@perturb.org>
Forked from Dstat written by Dag Wieers <dag@wieers.com>
Homepage at https://github.com/scottchiefbaker/dool/

Platform posix/linux
Kernel 6.10.7-100.fc39.x86_64
Python 3.12.5 (main, Aug  7 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)]
```

**Comment by scottchiefbaker** [comment]
Good news! I think we already do what you want [here](https://github.com/scottchiefbaker/dool/blob/master/dool#L1509).

If you set a `DOOL_TIMEFMT` environment variable to a string format that [`time.strftime()`](https://strftime.org/) understands it will work. This example will output just the hours, minutes, seconds.

```
export DOOL_TIMEFMT='%H:%M:%S' ; dool --time
```

**Comment by jsirianni** [comment]
Excellent, exactly what I need. Thanks!
