### ISSUE TITLE
When specfying `--output `-dool still prints on stdout

### ISSUE THREAD

**Issue by mucholove** [scottchiefbaker/dool#8]
When specfying `--output `-dool still prints on stdout.

I expected dool to exclusivley print to a file.

I fixed this on my local version by introducing an `if` statement inside the `perform ` function. (~/2868)

    if op.output and step == op.delay:
        outputfile.write(oline + '\n')
    else:
        sys.stdout.write(line + theme['input'])
        if op.debug:
           /,,,,

---

PS - Something else that is pretty weird is that the output dosen't follow the delay. The csv file is HUGE and adds several thousand lines every few seconds when it flushes. Not sure why

**Comment by xlight05** [comment]
+1. I tried running this on a bash script to perform. Couldn't get it done due to this issue.

**Comment by kmac** [comment]
As another datapoint, I prefer the current behaviour, so that I can monitor the data as it's being recorded.  You can always redirect the output to /dev/null in a script if you don't want it.

**Comment by tomchon** [comment]
The  output file was not written  until sending  ctrl+c to "dool --output test.log" . i think it's not proper....

**Comment by scottchiefbaker** [comment]
I just landed some code that addresses all of these things:

1. `--output /tmp/foo.csv` will output only to a file
2. Output file respects the delay again
3. Fixed the output going line by line to the file so you can run `tail -f` on it as it writes
4. Added a `--display` option so you can write to a file **and** display on your screen

Example: `dool --more --output /tmp/foo.csv --display 15`

Please test and let me know.

**Comment by scottchiefbaker** [comment]
This code has landed and will be in the next release.
